[package]
name = "code_exec_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
base64 = "0.21.2"
lazy_static = "1.4.0"
tokio = { version = "1.29.1", features = ["full"] }
